"""Patch sticker-generate-one.py with new vegetable + fruit plant lookup entries."""

script_path = r"C:\Users\RG\.openclaw\workspace\projects\garden-planner\tools\sticker-generate-one.py"

with open(script_path, 'rb') as f:
    raw = f.read()

# The line we want to insert before (binary search)
insert_marker = b'Fruit Trees'
idx = raw.find(insert_marker)
if idx == -1:
    print("ERROR: marker not found")
    exit(1)

# Go back to start of line
line_start = raw.rfind(b'\n', 0, idx) + 1
print(f"Inserting before byte {line_start}")

new_entries = b'''    # Vegetables - Leafy
    "arugula":               ("vegetable-leafy_arugula",          "S",  160, "Leafy Vegetable",  "plant",   "bright green #5AB83A, deep green #2A5A1A, pale green #8ABF6A, dark outline #0A1A0A", "Low rosette of deeply lobed peppery leaves with jagged toothed edges, stems at base, leaves arching outward."),
    "rocket":                ("vegetable-leafy_arugula",          "S",  160, "Leafy Vegetable",  "plant",   "bright green #5AB83A, deep green #2A5A1A, pale green #8ABF6A, dark outline #0A1A0A", "Low rosette of deeply lobed peppery leaves with jagged toothed edges, stems at base, leaves arching outward."),
    "radicchio":             ("vegetable-leafy_radicchio",        "S",  160, "Leafy Vegetable",  "plant",   "deep burgundy-red #8B1A2A, dark red #6B0A1A, pale cream-white veins #F5F0E8, dark outline #1A0A0A", "Compact tight round head of deep red-burgundy leaves with distinctive white veining, rosette form."),
    "endive":                ("vegetable-leafy_endive",           "S",  160, "Leafy Vegetable",  "plant",   "pale yellow-green #C8D870, mid green #5A8A3A, cream-white #F5F0E8, dark outline #0A1A0A", "Rosette of broad frilly curly-edged leaves in yellow-green, blanched pale inner leaves, ruffled texture."),
    "red amaranth":          ("vegetable-leafy_red-amaranth",     "M",  256, "Leafy Vegetable",  "plant",   "deep magenta-red #C41250, vivid red #E82050, deep green #2A5A1A, dark outline #1A0A0A", "Upright bushy plant with broad pointed leaves in striking deep red-magenta colour, stems at bottom."),
    "lamb\'s lettuce":       ("vegetable-leafy_lambs-lettuce",    "XS", 160, "Leafy Vegetable",  "plant",   "mid green #4A8A3A, bright green #6AAF5A, pale green #8ABF6A, dark outline #0A1A0A", "Tiny compact rosette of small rounded spoon-shaped leaves, very low-growing and tidy."),
    "mache":                 ("vegetable-leafy_lambs-lettuce",    "XS", 160, "Leafy Vegetable",  "plant",   "mid green #4A8A3A, bright green #6AAF5A, pale green #8ABF6A, dark outline #0A1A0A", "Tiny compact rosette of small rounded spoon-shaped leaves, very low-growing and tidy."),
    "new zealand spinach":   ("vegetable-leafy_nz-spinach",       "M",  256, "Leafy Vegetable",  "plant",   "mid green #4A8A3A, deep green #2A5A1A, bright green #6AAF5A, dark outline #0A1A0A", "Sprawling mat of thick fleshy triangular leaves on spreading stems, low groundcover habit."),
    "malabar spinach":       ("vegetable-leafy_malabar-spinach",  "M",  256, "Leafy Vegetable",  "plant",   "deep glossy green #1A6A3A, vivid green #3AAA5A, red stems #C84A2A, dark outline #0A1A0A", "Climbing vine with thick glossy heart-shaped leaves on fleshy red-purple stems."),
    "good king henry":       ("vegetable-leafy_good-king-henry",  "M",  256, "Leafy Vegetable",  "plant",   "mid green #4A8A3A, deep green #2A5A1A, pale mealy surface #C8D4B8, dark outline #0A1A0A", "Upright clump of large arrow-shaped leaves with mealy coating, upright flower spikes above."),
    "silverbeet":            ("vegetable-leafy_silverbeet",       "M",  256, "Leafy Vegetable",  "plant",   "deep green #1A6A3A, bright green #3AAA5A, pure white stems #F5F0E8, dark outline #0A1A0A", "Bold upright leaves with broad glossy green blade and thick white midrib and stems."),
    # Vegetables - Root
    "celeriac":              ("vegetable-root_celeriac",          "M",  256, "Root Vegetable",   "rootveg", "pale cream-tan bulb #D4C890, mid green tops #4A8A3A, celery-green #6AAF5A, dark outline #0A1A0A", "Rough knobbly round bulb peeking from soil line with upright celery-like green stalks above."),
    "jerusalem artichoke":   ("vegetable-root_jerusalem-artichoke", "XL", 512, "Root Vegetable", "rootveg", "bright yellow flowers #FFD700, deep green #2A5A1A, mid green #4A8A3A, pale tan tuber #D4B870, dark outline #0A1A0A", "Tall sunflower-like plant with golden-yellow blooms above and knobbly pale tubers peeking from soil line."),
    "salsify":               ("vegetable-root_salsify",           "M",  256, "Root Vegetable",   "rootveg", "pale cream root #F0E8C8, mid green strap tops #4A8A3A, purple flower #7B35C8, dark outline #0A1A0A", "Long slender pale root peeking from soil line with upright grass-like strap leaves and purple flower."),
    "scorzonera":            ("vegetable-root_scorzonera",        "M",  256, "Root Vegetable",   "rootveg", "deep black-brown root #2A1A0A, pale cream flesh hint #F0E8C8, mid green strap tops #4A8A3A, yellow flower #FFD700, dark outline #0A0A0A", "Long dark-skinned black root peeking from soil line with upright strap leaves and yellow dandelion-like flower."),
    "hamburg parsley":       ("vegetable-root_hamburg-parsley",   "M",  256, "Root Vegetable",   "rootveg", "pale cream root #F0E8C0, mid green #4A8A3A, bright green parsley #5AB83A, dark outline #0A1A0A", "Thick white parsnip-like root peeking from soil with curly bright green parsley-like tops above."),
    "sweet potato":          ("vegetable-root_sweet-potato",      "M",  256, "Root Vegetable",   "rootveg", "warm orange #E87820, deep orange #C45A10, bright green vines #5AB83A, heart-shaped leaves #4A8A3A, dark outline #0A1A0A", "Round orange sweet potato peeking from soil line with spreading heart-shaped vine leaves above."),
    "oca":                   ("vegetable-root_oca",               "S",  160, "Root Vegetable",   "rootveg", "vivid orange-yellow #E8A020, pale yellow #F5D070, bright green clover-like leaves #5AB83A, dark outline #0A1A0A", "Cluster of small bright orange-yellow tubers peeking from soil with small clover-like bright green leaves."),
    "skirret":               ("vegetable-root_skirret",           "M",  256, "Root Vegetable",   "rootveg", "pale cream roots #F0E8C8, mid green tops #4A8A3A, white flowers #F5F5E8, dark outline #0A1A0A", "Cluster of slender pale cream roots peeking from soil with upright ferny green tops and white flower clusters."),
    "yacon":                 ("vegetable-root_yacon",             "XL", 512, "Root Vegetable",   "rootveg", "warm tan tuber #C8A060, deep yellow-orange #D48830, bright green #5AB83A, broad leaves #3A8A3A, dark outline #0A1A0A", "Large daisy-like plant with big broad leaves above and large tan-golden tubers visible at soil line."),
    # Vegetables - Bulb
    "shallot":               ("vegetable-bulb_shallot",           "S",  160, "Bulb Vegetable",   "rootveg", "papery golden-brown #C8A050, pale copper #D4904A, bright green strap tops #4A8A3A, dark outline #1A0A0A", "Cluster of small papery golden-brown bulbs with multiple green strap shoots above, no soil."),
    "spring onion":          ("vegetable-bulb_spring-onion",      "S",  160, "Bulb Vegetable",   "rootveg", "pure white bulb #F5F0E8, pale green neck #C8D870, bright green strap tops #4A8A3A, dark outline #0A1A0A", "Slim white bulb base with long bright green hollow strap leaves above, clean floating view."),
    "scallion":              ("vegetable-bulb_spring-onion",      "S",  160, "Bulb Vegetable",   "rootveg", "pure white bulb #F5F0E8, pale green neck #C8D870, bright green strap tops #4A8A3A, dark outline #0A1A0A", "Slim white bulb base with long bright green hollow strap leaves above, clean floating view."),
    "elephant garlic":       ("vegetable-bulb_elephant-garlic",   "M",  256, "Bulb Vegetable",   "rootveg", "papery white #F5F0E8, pale purple tinge #C8B8D8, broad green strap #4A8A3A, dark outline #0A1A0A", "Very large single garlic bulb floating cleanly with broad flat strap leaves above, much bigger than regular garlic."),
    "florence fennel":       ("vegetable-bulb_florence-fennel",   "M",  256, "Bulb Vegetable",   "rootveg", "pale white-green bulb #D4E8C0, mid green #4A8A3A, feathery bright green fronds #6AAF5A, dark outline #0A1A0A", "Broad flat white-green fennel bulb with overlapping layers and feathery green fronds rising above."),
    "cipollini onion":       ("vegetable-bulb_cipollini",         "S",  160, "Bulb Vegetable",   "rootveg", "pale golden-brown #C8A050, cream white #F5F0D8, short green tops #4A8A3A, dark outline #0A1A0A", "Flat disc-shaped onion bulb, much wider than tall, papery golden-brown skin with short green tops."),
    "walking onion":         ("vegetable-bulb_walking-onion",     "M",  256, "Bulb Vegetable",   "rootveg", "mid green #4A8A3A, bright green #5AB83A, small topset bulbs #C8A050, dark outline #0A1A0A", "Upright hollow green stems with a cluster of small bulblets forming at the very top, arching under their weight."),
    "hardneck garlic":       ("vegetable-bulb_hardneck-garlic",   "S",  160, "Bulb Vegetable",   "rootveg", "papery white #F5F0E8, pale purple tinge #C8B8D8, stiff green scape #4A8A3A, dark outline #0A1A0A", "Papery garlic bulb floating cleanly with a stiff green scape curling into a loop above."),
    # Vegetables - Stem
    "globe artichoke":       ("vegetable-stem_globe-artichoke",   "XL", 512, "Stem Vegetable",   "plant",   "blue-grey green #6A8A7A, silver-green #8AAF8A, deep purple-green bud #4A5A3A, pale green bracts #A8C890, dark outline #0A1A10", "Architectural plant with large silver-green deeply divided leaves and one or more large round flower buds on tall stems."),
    "cardoon":               ("vegetable-stem_cardoon",           "XL", 512, "Stem Vegetable",   "plant",   "silver-grey #8AAFC0, pale silver #C8D8D0, violet-purple flower #7B35C8, dark outline #0A1018", "Massive architectural plant with large deeply-lobed silver-grey thistle-like leaves and tall spiny stems with purple flowers."),
    "bok choy":              ("vegetable-stem_bok-choy",          "S",  160, "Stem Vegetable",   "plant",   "bright green #5AB83A, deep green #2A5A1A, pure white stems #F5F0E8, dark outline #0A1A0A", "Compact rosette with broad glossy green leaves and thick crisp white stalks fanning from base."),
    "pak choi":              ("vegetable-stem_bok-choy",          "S",  160, "Stem Vegetable",   "plant",   "bright green #5AB83A, deep green #2A5A1A, pure white stems #F5F0E8, dark outline #0A1A0A", "Compact rosette with broad glossy green leaves and thick crisp white stalks fanning from base."),
    "samphire":              ("vegetable-stem_samphire",          "S",  160, "Stem Vegetable",   "plant",   "vivid bright green #5AB83A, blue-green #4A8A7A, succulent stems #8ABF8A, dark outline #0A1A10", "Low bushy succulent-stemmed coastal plant with finger-like cylindrical bright green stems and tiny yellow flowers."),
    # Vegetables - Fruiting
    "tomatillo":             ("vegetable-fruiting_tomatillo",     "M",  256, "Fruiting Vegetable", "plant", "mid green #4A8A3A, pale papery husk #D4C870, green-yellow fruit #A8C840, dark outline #0A1A0A", "Bushy plant with papery lantern-like husks enclosing green-yellow fruit, spreading habit."),
    "cape gooseberry":       ("vegetable-fruiting_cape-gooseberry", "M", 256, "Fruiting Vegetable", "plant", "mid green #4A8A3A, pale papery husk #D4C890, golden fruit #D4A020, dark outline #0A1A0A", "Upright bushy plant with distinctive papery lantern husks, golden-yellow round fruit visible inside split husks."),
    "ground cherry":         ("vegetable-fruiting_ground-cherry",  "S", 160, "Fruiting Vegetable", "plant", "mid green #4A8A3A, pale golden husk #D4C890, small yellow fruit #FFD700, dark outline #0A1A0A", "Compact low plant with small papery husks containing tiny golden cherry-like fruit."),
    "luffa":                 ("vegetable-fruiting_luffa",          "L", 384, "Fruiting Vegetable", "plant", "mid green #4A8A3A, deep green #2A5A1A, pale tan mature fruit #D4B870, bright green young fruit #6AAF5A, dark outline #0A1A0A", "Climbing vine with large green leaves and long pale green cylindrical sponge-gourd hanging from stem."),
    "armenian cucumber":     ("vegetable-fruiting_armenian-cucumber", "L", 384, "Fruiting Vegetable", "plant", "pale green #A8C870, mid green vine #4A8A3A, long curved fruit #8ABF5A, dark outline #0A1A0A", "Climbing vine with large leaves and very long slender curved pale green cucumber hanging."),
    "bitter melon":          ("vegetable-fruiting_bitter-melon",   "M", 256, "Fruiting Vegetable", "plant", "bright green #5AB83A, mid green vine #4A8A3A, vivid green warty fruit #3A8A2A, pale cream #D4C890, dark outline #0A1A0A", "Climbing vine with distinctive deeply warty bumpy-skinned oblong green fruit hanging from tendrils."),
    "butternut squash":      ("vegetable-fruiting_butternut-squash", "L", 384, "Fruiting Vegetable", "plant", "warm tan-cream #D4B870, pale golden #C8A050, broad green leaves #4A8A3A, orange flesh hint #E87820, dark outline #0A1A0A", "Sprawling plant with large broad leaves and distinctive pear-shaped butternut squash in warm tan-cream colour."),
    # Vegetables - Legumes
    "broad bean":            ("vegetable-legume_broad-bean",      "L",  384, "Legume",           "plant",   "mid green #4A8A3A, deep green #2A5A1A, pale cream flowers #F5F0E8, fat grey-green pods #7A9A6A, dark outline #0A1A0A", "Upright tall sturdy stems with pairs of grey-green leaves and large plump fat pods hanging from the plant."),
    "fava bean":             ("vegetable-legume_broad-bean",      "L",  384, "Legume",           "plant",   "mid green #4A8A3A, deep green #2A5A1A, pale cream flowers #F5F0E8, fat grey-green pods #7A9A6A, dark outline #0A1A0A", "Upright tall sturdy stems with pairs of grey-green leaves and large plump fat pods hanging from the plant."),
    "borlotti bean":         ("vegetable-legume_borlotti-bean",   "M",  256, "Legume",           "plant",   "mid green #4A8A3A, cream-red speckled pods #E8C8A0, vivid red-pink speckles #C84A4A, dark outline #0A1A0A", "Bushy plant with bright cream-pink speckled pods with red-pink markings, distinctive ornamental pods."),
    "chickpea":              ("vegetable-legume_chickpea",        "M",  256, "Legume",           "plant",   "mid green #4A8A3A, deep green #2A5A1A, pale cream pods #D4C890, white flowers #F5F0E8, dark outline #0A1A0A", "Compact bushy plant with small pinnate leaves and small plump cream pea-pods with 1-2 seeds visible."),
    "snow pea":              ("vegetable-legume_snow-pea",        "M",  256, "Legume",           "plant",   "bright green #5AB83A, deep green #2A5A1A, flat bright green pods #6AAF5A, white flowers #F5F0E8, dark outline #0A1A0A", "Climbing plant with tendrils and distinctive flat translucent-green pods showing seed outlines."),
    "snap pea":              ("vegetable-legume_snap-pea",        "M",  256, "Legume",           "plant",   "vivid green #5AB83A, deep green #2A5A1A, plump round pods #6AAF5A, white flowers #F5F0E8, dark outline #0A1A0A", "Climbing plant with tendrils and plump round-sectioned crisp snap pea pods."),
    "mangetout":             ("vegetable-legume_snap-pea",        "M",  256, "Legume",           "plant",   "vivid green #5AB83A, deep green #2A5A1A, plump round pods #6AAF5A, white flowers #F5F0E8, dark outline #0A1A0A", "Climbing plant with tendrils and plump round-sectioned crisp snap pea pods."),
    "lima bean":             ("vegetable-legume_lima-bean",       "M",  256, "Legume",           "plant",   "mid green #4A8A3A, deep green #2A5A1A, pale cream pods #D4C890, flat plump pods #C8C090, dark outline #0A1A0A", "Bushy plant with broad flat pale green-cream pods, each holding 2-3 plump flat butter beans."),
    "asparagus bean":        ("vegetable-legume_asparagus-bean",  "XL", 512, "Legume",           "plant",   "mid green #4A8A3A, deep green #2A5A1A, very long dark green pods #2A6A3A, dark outline #0A1A0A", "Climbing plant with enormously long pendant dark green pods hanging like ropes, 50-60cm length."),
    "yardlong bean":         ("vegetable-legume_asparagus-bean",  "XL", 512, "Legume",           "plant",   "mid green #4A8A3A, deep green #2A5A1A, very long dark green pods #2A6A3A, dark outline #0A1A0A", "Climbing plant with enormously long pendant dark green pods hanging like ropes, 50-60cm length."),
    "winged bean":           ("vegetable-legume_winged-bean",     "L",  384, "Legume",           "plant",   "mid green #4A8A3A, deep green #2A5A1A, bright green 4-winged pods #5AB83A, pale blue flower #A8C8E8, dark outline #0A1A0A", "Climbing tropical plant with distinctive 4-winged angular pods with frilly fins running the length."),
    # Vegetables - Brassica
    "sprouting broccoli":    ("vegetable-brassica_sprouting-broccoli", "L", 384, "Brassica",    "plant",   "deep purple-green #4A3A6A, vivid purple #7B35C8, mid green #4A8A3A, pale green #8ABF6A, dark outline #0A0A1A", "Tall branching plant with many small purple broccoli florets at shoot tips, leafy base."),
    "savoy cabbage":         ("vegetable-brassica_savoy-cabbage",  "M",  256, "Brassica",        "plant",   "deep blue-green #2A6A4A, mid green #4A8A5A, crinkled yellow-green #8ABF6A, dark outline #0A1A10", "Compact round head of deeply crinkled wavy-textured blue-green leaves, very textured surface."),
    "romanesco":             ("vegetable-brassica_romanesco",      "M",  256, "Brassica",        "plant",   "vivid yellow-green #8ABF2A, mid green #5A8A3A, pale lime-green #C8D870, geometric spirals #6A9A2A, dark outline #0A1A0A", "Striking fractal spiral head of vivid lime-green romanesco with perfect pointed logarithmic spirals radiating from centre."),
    # Vegetables - Asian Greens
    "pak choy":              ("vegetable-asian_pak-choy",          "S",  160, "Asian Green",      "plant",   "bright green #5AB83A, deep green #2A5A1A, pure white stems #F5F0E8, dark outline #0A1A0A", "Compact rosette of glossy bright green leaves on thick white crunchy stems, very clean and fresh."),
    "napa cabbage":          ("vegetable-asian_napa-cabbage",      "M",  256, "Asian Green",      "plant",   "pale yellow-green #C8D870, mid green #4A8A3A, cream-white centre #F5F0E8, dark outline #0A1A0A", "Tall oval-shaped head of pale crinkly yellow-green leaves forming a tight elongated barrel shape."),
    "chinese cabbage":       ("vegetable-asian_napa-cabbage",      "M",  256, "Asian Green",      "plant",   "pale yellow-green #C8D870, mid green #4A8A3A, cream-white centre #F5F0E8, dark outline #0A1A0A", "Tall oval-shaped head of pale crinkly yellow-green leaves forming a tight elongated barrel shape."),
    "mizuna":                ("vegetable-asian_mizuna",            "S",  160, "Asian Green",      "plant",   "bright green #5AB83A, mid green #4A8A3A, deep green #2A5A1A, pale stems #D4E8C0, dark outline #0A1A0A", "Low spreading rosette of deeply pinnate feathery bright green leaves with narrow lobes, very frilly."),
    "tatsoi":                ("vegetable-asian_tatsoi",            "S",  160, "Asian Green",      "plant",   "deep glossy green #1A6A3A, mid green #3A8A5A, white stems #F5F0E8, dark outline #0A1A10", "Perfect flat rosette of deep glossy rounded spoon-shaped leaves spreading symmetrically from centre."),
    "garland chrysanthemum": ("vegetable-asian_garland-chrysanthemum", "M", 256, "Asian Green",  "plant",   "bright green #5AB83A, mid green #4A8A3A, golden-yellow flowers #FFD700, pale yellow #FFE870, dark outline #0A1A0A", "Bushy plant with finely divided aromatic leaves and bright golden daisy-like flowers at tips."),
    "water spinach":         ("vegetable-asian_water-spinach",    "M",  256, "Asian Green",      "plant",   "vivid green #5AB83A, deep green #2A6A3A, pale stems #D4E8C0, hollow stems #8ABF6A, dark outline #0A1A0A", "Sprawling aquatic plant with hollow stems and arrow-shaped vivid green leaves."),
    "chinese spinach":       ("vegetable-asian_chinese-spinach",  "M",  256, "Asian Green",      "plant",   "deep magenta-red #C41250, vivid red #E82050, deep green #2A5A1A, dark outline #1A0A0A", "Upright bushy plant with broad pointed leaves in striking red-green colouring."),
    # Vegetables - Perennial
    "sea kale":              ("vegetable-perennial_sea-kale",     "M",  256, "Perennial Vegetable", "plant", "blue-grey green #6A8A9A, silver-blue #8AAFC0, white flowers #F5F0E8, dark outline #0A1018", "Bold architectural plant with large blue-grey wavy-edged leaves and dense clusters of small white flowers on tall stems."),
    "nine-star broccoli":    ("vegetable-perennial_nine-star-broccoli", "L", 384, "Perennial Vegetable", "plant", "deep blue-green #2A6A4A, mid green #4A8A5A, pale cream-white heads #F0EEE0, dark outline #0A1A10", "Large perennial brassica plant with multiple small creamy-white sprouting broccoli heads at branch tips."),
    "turkish rocket":        ("vegetable-perennial_turkish-rocket", "M", 256, "Perennial Vegetable", "plant", "mid green #4A8A3A, bright green #5AB83A, vivid yellow flowers #FFD700, pale green #8ABF6A, dark outline #0A1A0A", "Bushy leafy plant with bright green lobed leaves and clusters of small vivid yellow mustard-family flowers."),
    "perennial leek":        ("vegetable-perennial_perennial-leek", "M", 256, "Perennial Vegetable", "plant", "blue-green strap #6A9A7A, mid green #4A8A5A, purple-pink allium ball #C87890, pale strap #8AAFA0, dark outline #0A1A10", "Upright blue-green strap-leaved plant with a decorative round purple-pink allium flower head at top."),
    # Fruit - Stone
    "apricot":               ("tree-fruit_apricot",               "L",  384, "Stone Fruit",      "deciduous", "deep green #2A5C1A, mid-green #4A8C3A, warm golden-orange apricot #E89040, warm brown limbs #6B3A2A, pale yellow-green #B8D474", "Natural rounded leafy canopy. Small clusters of warm golden-orange apricot fruit as accent. Canopy fills the frame."),
    "nectarine":             ("tree-fruit_nectarine",             "L",  384, "Stone Fruit",      "deciduous", "deep green #2A5C1A, mid-green #4A8C3A, vivid red-yellow nectarine #D44A2A, warm brown limbs #6B3A2A, pale yellow-green #B8D474", "Natural rounded leafy deciduous canopy. Red-yellow smooth-skinned nectarine fruit as accent. Canopy fills the frame."),
    "damson":                ("tree-fruit_damson",                "M",  256, "Stone Fruit",      "deciduous", "deep green #2A5C1A, mid-green #4A8C3A, deep purple-blue damson #4A2A7A, warm brown limbs #6B3A2A, pale yellow-green #B8D474", "Natural compact rounded canopy. Small deep purple-blue damson plums as accent. Canopy fills the frame."),
    "greengage":             ("tree-fruit_greengage",             "M",  256, "Stone Fruit",      "deciduous", "deep green #2A5C1A, mid-green #4A8C3A, golden-green greengage #A8C840, warm brown limbs #6B3A2A, pale yellow-green #B8D474", "Natural rounded compact canopy. Small golden-green round plum fruit as accent. Canopy fills the frame."),
    "sloe":                  ("tree-fruit_sloe",                  "M",  256, "Stone Fruit",      "deciduous", "deep green #2A5C1A, mid-green #4A8C3A, blue-black sloe berries #2A1A4A, white blossom #F8F8F0, warm brown limbs #6B3A2A", "Compact spiny shrub-like canopy with white spring blossom and clusters of tiny blue-black sloe berries."),
    "blackthorn":            ("tree-fruit_sloe",                  "M",  256, "Stone Fruit",      "deciduous", "deep green #2A5C1A, mid-green #4A8C3A, blue-black sloe berries #2A1A4A, white blossom #F8F8F0, warm brown limbs #6B3A2A", "Compact spiny shrub-like canopy with white spring blossom and clusters of tiny blue-black sloe berries."),
    "mirabelle":             ("tree-fruit_mirabelle",             "M",  256, "Stone Fruit",      "deciduous", "deep green #2A5C1A, mid-green #4A8C3A, golden-yellow mirabelle #FFD700, warm brown limbs #6B3A2A, pale yellow-green #B8D474", "Natural rounded compact canopy. Clusters of tiny golden-yellow round mirabelle plums as accent. Canopy fills the frame."),
    "almond":                ("tree-fruit_almond",                "L",  384, "Stone Fruit",      "deciduous", "deep green #2A5C1A, mid-green #4A8C3A, pale pink blossom #F5C8D8, green velvet hull #8ABF5A, warm brown limbs #6B3A2A", "Natural spreading canopy. Pale pink spring blossom and green velvety almond hulls as accents. Canopy fills the frame."),
    # Fruit - Citrus
    "orange":                ("tree-fruit_orange",                "L",  384, "Citrus Fruit",     "deciduous", "deep glossy green #1A6A3A, mid-green #3A8A5A, vivid orange fruit #E87820, warm brown limbs #6B3A2A, pale yellow #D4C870", "Dense glossy evergreen canopy with vivid round orange fruits as accent. Canopy fills the frame."),
    "lime":                  ("tree-fruit_lime",                  "M",  256, "Citrus Fruit",     "deciduous", "deep glossy green #1A6A3A, mid-green #3A8A5A, vivid lime-green fruit #6ABF2A, warm brown limbs #6B3A2A, bright green #8ABF5A", "Dense compact glossy canopy with vivid small round lime-green fruits as accent. Canopy fills the frame."),
    "grapefruit":            ("tree-fruit_grapefruit",            "L",  384, "Citrus Fruit",     "deciduous", "deep glossy green #1A6A3A, mid-green #3A8A5A, pale golden-yellow grapefruit #E8D050, warm brown limbs #6B3A2A, bright green #8ABF5A", "Dense glossy canopy with large pale golden-yellow grapefruit as accent. Canopy fills the frame."),
    "mandarin":              ("tree-fruit_mandarin",              "M",  256, "Citrus Fruit",     "deciduous", "deep glossy green #1A6A3A, mid-green #3A8A5A, vivid orange mandarin #E87020, warm brown limbs #6B3A2A, bright green #8ABF5A", "Compact glossy canopy with clusters of small vivid orange mandarin fruits as accent. Canopy fills the frame."),
    "clementine":            ("tree-fruit_mandarin",              "M",  256, "Citrus Fruit",     "deciduous", "deep glossy green #1A6A3A, mid-green #3A8A5A, vivid orange mandarin #E87020, warm brown limbs #6B3A2A, bright green #8ABF5A", "Compact glossy canopy with clusters of small vivid orange mandarin fruits as accent. Canopy fills the frame."),
    "meyer lemon":           ("tree-fruit_meyer-lemon",           "M",  256, "Citrus Fruit",     "deciduous", "deep glossy green #1A6A3A, mid-green #3A8A5A, pale golden-yellow lemon #E8D050, warm brown limbs #6B3A2A, bright green #8ABF5A", "Compact bushy glossy canopy with round pale golden-yellow meyer lemons as accent. Rounder softer than regular lemon."),
    "kumquat":               ("tree-fruit_kumquat",               "S",  160, "Citrus Fruit",     "deciduous", "deep glossy green #1A6A3A, mid-green #3A8A5A, vivid orange kumquat #E87020, warm brown limbs #6B3A2A, bright green #8ABF5A", "Small compact glossy shrub with clusters of tiny oval vivid orange kumquat fruits. Much smaller than other citrus."),
    "blood orange":          ("tree-fruit_blood-orange",          "M",  256, "Citrus Fruit",     "deciduous", "deep glossy green #1A6A3A, mid-green #3A8A5A, deep red-orange fruit #C84A2A, dark crimson blush #8B1A2A, warm brown limbs #6B3A2A", "Dense glossy canopy with distinctive deep red-blushed orange fruits. Darker more dramatic colour than regular orange."),
    "pomelo":                ("tree-fruit_pomelo",                "L",  384, "Citrus Fruit",     "deciduous", "deep glossy green #1A6A3A, mid-green #3A8A5A, very large pale green-yellow pomelo #C8D870, warm brown limbs #6B3A2A, bright green #8ABF5A", "Dense glossy canopy with very large pale greenish-yellow pomelo fruits, noticeably bigger than other citrus."),
    # Fruit - Berry
    "strawberry":            ("fruit-berry_strawberry",           "XS", 160, "Berry Fruit",      "plant",   "vivid red #D42B2B, deep red #A01A1A, bright green trifoliate leaves #5AB83A, pale pink flower #F5C8D8, dark outline #1A0A0A", "Low spreading mat of trifoliate toothed leaves with bright red heart-shaped strawberries and runners."),
    "white currant":         ("fruit-berry_white-currant",        "S",  160, "Berry Fruit",      "plant",   "mid green #4A8A3A, pale translucent white berries #F5F0E8, cream-white clusters #E8E0D0, dark outline #0A1A0A", "Compact bushy shrub with drooping strigs of translucent pale white-cream currant berries."),
    "boysenberry":           ("fruit-berry_boysenberry",          "M",  256, "Berry Fruit",      "plant",   "deep purple-red #6B1A2A, vivid dark red #8B2A2A, mid green cane #4A8A3A, pale pink blossom #F5C8D8, dark outline #1A0A1A", "Arching cane with deeply lobed leaves and large dark purple-red compound berries."),
    "loganberry":            ("fruit-berry_loganberry",           "M",  256, "Berry Fruit",      "plant",   "deep red #8B1A2A, vivid red #C42A2A, mid green cane #4A8A3A, pale pink blossom #F5C8D8, dark outline #1A0A0A", "Arching cane with lobed leaves and elongated dark red compound berries, longer than raspberry."),
    "tayberry":              ("fruit-berry_tayberry",             "M",  256, "Berry Fruit",      "plant",   "deep purple-red #7B1A2A, vivid red #B82A2A, mid green cane #4A8A3A, pale pink blossom #F5C8D8, dark outline #1A0A1A", "Arching cane with lobed leaves and large elongated deep purple-red compound berries."),
    # Fruit - Vine
    "table grape":           ("fruit-vine_table-grape",           "XL", 512, "Vine Fruit",       "plant",   "mid green #4A8A3A, deep green #2A5A1A, deep purple-black grapes #3A1A5A, pale green grapes #C8D870, dark outline #0A0A1A", "Climbing vine with large lobed leaves and hanging pendulous clusters of round grapes in deep purple-black."),
    "wine grape":            ("fruit-vine_wine-grape",            "XL", 512, "Vine Fruit",       "plant",   "mid green #4A8A3A, deep green #2A5A1A, deep burgundy grapes #5A1A3A, pale green autumn leaves #C8D870, dark outline #0A0A1A", "Climbing vine with lobed leaves and tight dense clusters of small dark burgundy wine grapes."),
    "kiwi":                  ("fruit-vine_kiwi",                  "XL", 512, "Vine Fruit",       "plant",   "deep green #2A6A3A, mid green #4A8A5A, brown fuzzy kiwi #8A5A2A, pale cream flesh hint #F0E8C8, dark outline #0A1A10", "Vigorous climbing vine with large heart-shaped leaves and clusters of oval fuzzy brown kiwifruit."),
    "hardy kiwi":            ("fruit-vine_hardy-kiwi",            "XL", 512, "Vine Fruit",       "plant",   "deep green #2A6A3A, mid green #4A8A5A, smooth green mini kiwi #6AAF3A, pale green #A8C870, dark outline #0A1A10", "Climbing vine with smaller leaves and clusters of smooth small grape-sized green kiwi fruit."),
    "passion fruit":         ("fruit-vine_passion-fruit",         "XL", 512, "Vine Fruit",       "plant",   "mid green #4A8A3A, deep green #2A6A3A, vivid purple passion fruit #5A1A7A, exotic purple-white flower #9A5AC8, dark outline #0A0A1A", "Climbing vine with exotic star-shaped purple-white flowers and round deep purple passion fruits."),
    "dragon fruit":          ("fruit-vine_dragon-fruit",          "L",  384, "Vine Fruit",       "plant",   "vivid pink #E8208A, deep green ribs #2A6A3A, white flesh hint #F5F0E8, green scale tips #5AB83A, dark outline #1A0A2A", "Climbing cactus-like vine with vivid hot pink scaled fruit with green-tipped scales and trailing stems."),
    # Fruit - Tropical
    "mango":                 ("tree-fruit_mango",                 "XL", 512, "Tropical Fruit",   "deciduous", "deep green #1A6A3A, glossy mid-green #3A8A5A, vivid golden-red mango #E87820, deep red blush #C84A2A, warm brown limbs #6B3A2A", "Dense spreading glossy-leaved canopy with vivid golden-orange mango fruit with red blush as accent."),
    "papaya":                ("tree-fruit_papaya",                "L",  384, "Tropical Fruit",   "plant",   "deep green #1A6A3A, mid-green #3A8A5A, golden-orange papaya #E8A020, pale yellow #D4C870, green stem trunk #4A8A5A, dark outline #0A1A10", "Tall unbranched trunk with crown of large deeply-lobed star-shaped leaves and cluster of large golden-orange papaya fruits at crown."),
    "guava":                 ("tree-fruit_guava",                 "L",  384, "Tropical Fruit",   "deciduous", "deep green #1A6A3A, mid-green #3A8A5A, pale yellow-green guava #C8D870, warm pink blush #E8A090, warm brown limbs #6B3A2A", "Rounded compact canopy with oval pale yellow-green guava fruits with subtle pink blush as accent."),
    "avocado":               ("tree-fruit_avocado",               "XL", 512, "Tropical Fruit",   "deciduous", "deep glossy green #1A6A3A, mid-green #3A8A5A, dark purple-green avocado #3A4A2A, warm brown limbs #6B3A2A, pale yellow-green #B8D474", "Spreading glossy-leaved canopy with distinctive pear-shaped dark purple-green avocado fruit as accent."),
    "lychee":                ("tree-fruit_lychee",                "L",  384, "Tropical Fruit",   "deciduous", "deep glossy green #1A6A3A, mid-green #3A8A5A, vivid red lychee #C42A2A, pale pink #F5A0A0, warm brown limbs #6B3A2A", "Dense rounded canopy with clusters of small bright red warty-skinned lychee fruits as accent."),
    "pineapple":             ("fruit-tropical_pineapple",         "M",  256, "Tropical Fruit",   "plant",   "golden-yellow #D4A020, vivid yellow #E8C040, deep green crown #2A6A3A, spiky blue-green leaves #5A8A7A, dark outline #0A1A10", "Ground-growing plant with stiff spiky blue-green bromeliad leaves and a large golden-yellow pineapple at centre."),
    "starfruit":             ("tree-fruit_starfruit",             "L",  384, "Tropical Fruit",   "deciduous", "deep green #1A6A3A, mid-green #3A8A5A, vivid golden-yellow starfruit #D4C040, warm brown limbs #6B3A2A, pale yellow-green #B8D474", "Rounded spreading canopy with distinctive golden-yellow star-shaped carambola fruits as accent."),
    "carambola":             ("tree-fruit_starfruit",             "L",  384, "Tropical Fruit",   "deciduous", "deep green #1A6A3A, mid-green #3A8A5A, vivid golden-yellow starfruit #D4C040, warm brown limbs #6B3A2A, pale yellow-green #B8D474", "Rounded spreading canopy with distinctive golden-yellow star-shaped carambola fruits as accent."),
    "feijoa":                ("tree-fruit_feijoa",                "L",  384, "Tropical Fruit",   "deciduous", "deep green #1A6A3A, grey-green #7A9A7A, oval green-grey feijoa #8AAF7A, vivid red-pink flower #E8207A, warm brown limbs #6B3A2A", "Compact rounded canopy with silvery-green leaves and oval feijoa fruits and exotic red-pink flowers as accent."),
    "jaboticaba":            ("tree-fruit_jaboticaba",            "M",  256, "Tropical Fruit",   "deciduous", "deep green #1A6A3A, mid-green #3A8A5A, deep purple-black berries #1A0A2A, warm brown trunk #6B3A2A, pale bark #C8B8A8", "Unusual shrub-tree with fruit growing directly on the trunk and main branches in clusters of deep purple-black berries."),
    "jackfruit":             ("tree-fruit_jackfruit",             "XXL", 512, "Tropical Fruit",  "deciduous", "deep green #1A6A3A, mid-green #3A8A5A, enormous green-brown jackfruit #8A7A4A, spiky skin #6A5A3A, warm brown trunk #6B3A2A", "Large tropical canopy with truly enormous spiky oval jackfruit visible on the trunk and branches."),
    # Fruit - Melons
    "watermelon":            ("fruit-melon_watermelon",           "L",  384, "Melon",            "plant",   "deep green stripes #2A6A3A, pale green stripes #8ABF6A, vivid red flesh hint #C42A2A, mid green vines #4A8A3A, dark outline #0A1A0A", "Sprawling vine with large green leaves and a big round watermelon with distinctive dark and light green stripes."),
    "cantaloupe":            ("fruit-melon_cantaloupe",           "M",  256, "Melon",            "plant",   "tan-cream netting #C8A870, warm golden #D4A050, orange flesh hint #E87820, mid green vine #4A8A3A, dark outline #0A1A0A", "Compact vine with large leaves and a round tan-netted cantaloupe melon with orange flesh visible at stem end."),
    "honeydew":              ("fruit-melon_honeydew",             "M",  256, "Melon",            "plant",   "smooth pale green-cream #C8D8B8, pale yellow #D4C870, cool white-green #D8E8D0, mid green vine #4A8A3A, dark outline #0A1A10", "Compact vine with large leaves and a smooth oval pale cream-green honeydew melon."),
    "charentais melon":      ("fruit-melon_charentais",           "M",  256, "Melon",            "plant",   "pale grey-green #B8C8B0, subtle ribbing #A8B8A0, vivid orange flesh hint #E87820, mid green vine #4A8A3A, dark outline #0A1A10", "Compact vine with a small pale grey-green round ribbed charentais melon, intensely aromatic French variety."),
    "galia melon":           ("fruit-melon_galia",                "M",  256, "Melon",            "plant",   "tan netted skin #C8A870, pale green-gold #C8C870, mid green vine #4A8A3A, dark outline #0A1A0A", "Compact vine with a netted-skin galia melon, similar to cantaloupe but with greenish-gold interior."),
    "winter melon":          ("fruit-melon_winter-melon",         "XL", 512, "Melon",            "plant",   "deep green wax #2A6A4A, pale waxy blue-green #7A9A8A, white waxy bloom #E8EEE8, mid green vine #4A8A3A, dark outline #0A1A10", "Large climbing vine with enormous pale waxy blue-green oblong winter melon with white powdery bloom."),
    # Fruit - Nuts
    "walnut":                ("tree-nut_walnut",                  "XXL", 512, "Nut",             "deciduous", "deep green #2A5C1A, mid-green #4A8C3A, green-hulled walnut #5A7A3A, pale brown nut #C8A870, warm brown limbs #6B3A2A", "Massive spreading canopy with large pinnate leaves and round green-hulled walnuts as accent."),
    "chestnut":              ("tree-nut_chestnut",                "XXL", 512, "Nut",             "deciduous", "deep green #2A5C1A, mid-green #4A8C3A, spiky green burr #5A7A3A, warm brown chestnut #8A5A2A, warm brown limbs #6B3A2A", "Large spreading canopy with distinctive spiky green burrs containing shiny brown chestnuts as accent."),
    "pecan":                 ("tree-nut_pecan",                   "XL", 512, "Nut",             "deciduous", "deep green #2A5C1A, mid-green #4A8C3A, elongated tan pecan #C8A870, warm brown limbs #6B3A2A, pale yellow-green #B8D474", "Large spreading canopy with long pinnate leaves and elongated oval tan pecan nuts in green husks as accent."),
    "macadamia":             ("tree-nut_macadamia",               "L",  384, "Nut",             "plant",   "deep glossy green #1A6A3A, mid-green #3A8A5A, round tan macadamia #C8A870, white flower spike #F5F0E8, dark outline #0A1A10", "Dense evergreen canopy with long glossy leaves and clusters of round hard-shelled macadamia nuts on strings."),
    "pistachio":             ("tree-nut_pistachio",               "L",  384, "Nut",             "deciduous", "deep green #2A5C1A, mid-green #4A8C3A, pale tan split shell #D4B870, vivid green nut #6AAF3A, warm brown limbs #6B3A2A", "Spreading compact canopy with clusters of tan split-shell pistachio nuts showing vivid green nut inside as accent."),
'''

# Do the binary insert
new_raw = raw[:line_start] + new_entries + raw[line_start:]

with open(script_path, 'wb') as f:
    f.write(new_raw)

print(f"Done. File size: {len(new_raw)} bytes")
# Verify
with open(script_path, 'rb') as f:
    check = f.read()
print(f"'arugula' in file: {b'arugula' in check}")
print(f"'walnut' in file: {b'walnut' in check}")
